In [6]:
import pandas as pd
from huggingface_hub import snapshot_download
import json

repo_path = snapshot_download(repo_id="7vik/amongus", repo_type="dataset")

file_path = f"{repo_path}/expt-logs/2025-02-01_llama_llama_100_games_v3/agent-logs-compact.json"

with open(file_path, "r") as f:
    data = list(map(json.loads, f))

df = pd.DataFrame(data)

Fetching 19 files:   0%|          | 0/19 [00:00<?, ?it/s]

In [7]:
df

,game_index,step,timestamp,player,interaction
0,Game 43,0,2025-02-01 05:37:57.045632,"{'name': 'Player 1: orange', 'identity': 'Crew...",{'system_prompt': ' You are Player 1: orange. ...
1,Game 76,0,2025-02-01 05:37:57.085564,"{'name': 'Player 1: orange', 'identity': 'Crew...",{'system_prompt': ' You are Player 1: orange. ...
2,Game 4,0,2025-02-01 05:37:57.120568,"{'name': 'Player 1: red', 'identity': 'Crewmat...",{'system_prompt': ' You are Player 1: red. You...
3,Game 31,0,2025-02-01 05:37:57.211343,"{'name': 'Player 1: lime', 'identity': 'Crewma...",{'system_prompt': ' You are Player 1: lime. Yo...
4,Game 68,0,2025-02-01 05:37:57.249463,"{'name': 'Player 1: orange', 'identity': 'Impo...",{'system_prompt': ' You are Player 1: orange. ...
...,...,...,...,...,...
7945,Game 34,18,2025-02-01 06:16:41.721168,"{'name': 'Player 4: brown', 'identity': 'Impos...",{'system_prompt': ' You are Player 4: brown. Y...
7946,Game 97,15,2025-02-01 06:16:53.868193,"{'name': 'Player 3: lime', 'identity': 'Impost...",{'system_prompt': ' You are Player 3: lime. Yo...
7947,Game 97,15,2025-02-01 06:17:02.989332,"{'name': 'Player 6: orange', 'identity': 'Crew...",{'system_prompt': ' You are Player 6: orange. ...
7948,Game 34,18,2025-02-01 06:17:03.458641,"{'name': 'Player 5: cyan', 'identity': 'Crewma...",{'system_prompt': ' You are Player 5: cyan. Yo...
7949,Game 34,18,2025-02-01 06:17:06.738716,"{'name': 'Player 7: green', 'identity': 'Crewm...",{'system_prompt': ' You are Player 7: green. Y...